config/routes.rb
Rails.application.routes.draw do
  get 'charges/new'
  get 'charges/create'
  get 'profile/index'
  get 'profile/create'
  get 'profile/update'
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Cart Modifications
  get 'cart/add_to_cart', to: "cart#addToCart"
  get 'cart/remove_from_cart', to: "cart#removeFromCart"
  get 'checkout' , to:"cart#checkout"

  # My Profile
  get 'profile/create', to: "profile#create"
  get 'profile/index', to: "profile#index"
  get 'profile/update', to: "profile#update"

  #Orders
  get 'order/add_order', to: 'order#add_order'

  # Stripe routes
  resources :charges, only: [:new, :create]



  resources :products, only: [:show, :index]
  resources :categories, only: [:show, :index]
  resources :pages, only: [:show, :index]
  resources :search, only: [:index] do
    collection do
      get 'results'
    end
  end
  resources :cart, only: [:index]


  get ':permalink', to: 'pages#permalink'

  root 'products#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  mount_uploader :icon, IconUploader
end

app/models/order.rb
class Order < ApplicationRecord
  validates :user_id , :total_price, :status_type_id , presence:true

  belongs_to :user
  belongs_to :status_type

  has_many :ordered_products, dependent: :destroy
  has_many :products, through: :ordered_products, dependent: :destroy
  accepts_nested_attributes_for :ordered_products

end

app/models/ordered_product.rb
class OrderedProduct < ApplicationRecord

  validates :product_id, :order_id, :quantity, :price, presence: true
  validates :quantity, numericality: {greater_than: 0}

  belongs_to :product
  belongs_to :order
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :description, :category,  presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 1}
  validates :name, uniqueness:true

  belongs_to :category
  has_many :ordered_products, dependent: :destroy
  has_many :orders, through: :ordered_products, dependent: :destroy
  belongs_to :status_type

  mount_uploader :image, ImageUploader
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_one :user
  belongs_to :tax
end

app/models/status_type.rb
class StatusType < ApplicationRecord
  validates :name, uniqueness: true
  has_many :products
  has_many :orders
end

app/models/tax.rb
class Tax < ApplicationRecord
  validates :GST, :PST, presence: true
  has_many :profiles
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def index
    add_breadcrumb "Cart"
  end

  def show
  end

  def addToCart
    session[:cart] ||= []
    session[:cart] << {:id =>params[:id], :qty =>params[:quantity], :price =>params[:price]}

    redirect_to cart_index_path
  end

  def removeFromCart
    if(params[:submit] == "Remove")
      session[:cart].delete_at(params[:number].to_i)
    else
      session[:cart][params[:number].to_i]["qty"] = params[:qty].to_i
    end

    redirect_to cart_index_path
  end

  def checkout
    add_breadcrumb "Cart", cart_index_path
    add_breadcrumb "Checkout", checkout_path

    @total_amount = (session[:total_price].to_f * 100 ).round(0)
    province = @profile.tax
    @taxes = (province.GST + province.PST).round(2)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/status_types_helper.rb
module StatusTypesHelper
end

app/views/cart/checkout.html.erb
<div class="row float-left">
  <div class="col-12 p-5">
    <h3>Please check your details:</h3>
    <table class="table">
      <tbody>
        <tr>
          <th>Full Name</th>
          <td><%= @profile.name%></td>
        </tr>
        <tr>
          <th>Email</th>
          <td><%= @profile.user.email%></td>
        </tr>
        <tr>
          <th>Contact</th>
          <td><%= @profile.phone%></td>
        </tr>
        <tr>
          <th>Address</th>
          <td><%= @profile.address%></td>
        </tr>
        <tr>
          <th>City</th>
          <td><%= @profile.city%></td>
        </tr>
        <tr>
          <th>Province</th>
          <td><%= @profile.tax.province%></td>
        </tr>
        <tr>
          <th>Zip</th>
          <td><%= @profile.zip%></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<div class="row float-right">
<div class="col-3 p-5">
  <div class="display-4">Invoice</div>
    <table class="table table-borderless">
      <thead>
        <tr>
          <th scope="col">Product</th>
          <th scope="col">Qty</th>
          <th scope="col">Price</th>
        </tr>
      </thead>
      <tbody>
        <% subtotal = 0 %>
        <%session[:cart].each do |item|%>
          <% @product = Product.find(item["id"])%>
          <tr>
            <td><%= link_to @product.name, @product%></td>
            <td><%=item["qty"]%></td>
            <td><%=item["price"]%></td>
            <% subtotal += item["price"].to_d%>
          </tr>
        <%end%>
        <tr>
          <th></th>
          <th scope="row">Subtotal: </th>
          <td>$<%= subtotal%></td>
        </tr>
        <tr>
          <th></th>
          <th scope="row">Taxes: </th>
          <td>$<%= taxes = (@taxes*subtotal).round(2)  %></td>
        </tr>
        <tr>
          <th></th>
          <th scope="row">Total: </th>
          <td>$<%= session[:total_price] = taxes+subtotal %></td>
        </tr>
      </tbody>
    </table>
    <%= render template: "charges/new" , :locals => { amount: @total_amount} %>
  </div>
</div>
</div>

app/views/cart/index.html.erb
<h1>Cart</h1>

<%if session[:cart] && session[:cart] != []%>
  <table class="table" id="cart_table">
    <thead>
      <tr>
      <th scope="col">Image</th>
        <th scope="col">Product Name</th>
        <th scope="col">Price</th>
        <th scope="col">Quantity</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
    <% rank = -1; %>
    <%session[:cart].each do |item|%>
      <% @product = Product.find(item["id"])%>
      <%rank = rank.to_i + 1%>
      <form method="get" action="<%= cart_remove_from_cart_path %>">
        <tr>
          <input name="number" type="hidden" value="<%=rank%>">
          <td><%= image_tag @product.image.thumb.url%></td>
          <td><%=link_to @product.name, @product%></td>
          <td>$<%=item["price"]%></td>
          <td><input name ="qty" id="qty" type="number" value ="<%=item["qty"]%>"></td>
          <td><button class="btn" type="submit">Change Quantity</button></td>
          <td><button name="submit" class="btn" type="submit" value="Remove">Remove</button></td>
        </tr>
      </form>
      <%end%>
    </tbody>
  </table>
  <% if user_signed_in?%>
    <% if current_user.username %>
      <a class="btn btn-secondary btn-lg btn-block" href="<%= checkout_path%>" role="button">Checkout >></a>
    <% else %>
      <a class="btn btn-secondary btn-lg btn-block" href="<%= profile_create_path%>" role="button">Please fill out your profile >></a>
    <% end %>

  <% else%>
    <a class="btn btn-secondary btn-lg btn-block" href="<%= new_user_session_path %>" role="button">Please sign in to continue >></a>
  <% end%>
<%else%>
  <div class='m-5 p-5'><h1>Oops! No items in the cart.</h1></div>
<%end%>