config/routes.rb
Rails.application.routes.draw do
  get 'charges/new'
  get 'charges/create'
  get 'profile/index'
  get 'profile/create'
  get 'profile/update'
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Cart Modifications
  get 'cart/add_to_cart', to: "cart#addToCart"
  get 'cart/remove_from_cart', to: "cart#removeFromCart"
  get 'checkout' , to:"cart#checkout"

  # My Profile
  get 'profile/create', to: "profile#create"
  get 'profile/index', to: "profile#index"
  get 'profile/update', to: "profile#update"

  #Orders
  get 'order/add_order', to: 'order#add_order'

  # Stripe routes
  resources :charges, only: [:new, :create]



  resources :products, only: [:show, :index]
  resources :categories, only: [:show, :index]
  resources :pages, only: [:show, :index]
  resources :search, only: [:index] do
    collection do
      get 'results'
    end
  end
  resources :cart, only: [:index]


  get ':permalink', to: 'pages#permalink'

  root 'products#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  mount_uploader :icon, IconUploader
end

app/models/order.rb
class Order < ApplicationRecord
  validates :user_id , :total_price, :status_type_id , presence:true

  belongs_to :user
  belongs_to :status_type

  has_many :ordered_products, dependent: :destroy
  has_many :products, through: :ordered_products, dependent: :destroy
  accepts_nested_attributes_for :ordered_products

end

app/models/ordered_product.rb
class OrderedProduct < ApplicationRecord

  validates :product_id, :order_id, :quantity, :price, presence: true
  validates :quantity, numericality: {greater_than: 0}

  belongs_to :product
  belongs_to :order
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :description, :category,  presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 1}
  validates :name, uniqueness:true

  belongs_to :category
  has_many :ordered_products, dependent: :destroy
  has_many :orders, through: :ordered_products, dependent: :destroy
  belongs_to :status_type

  mount_uploader :image, ImageUploader
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_one :user
  belongs_to :tax
end

app/models/status_type.rb
class StatusType < ApplicationRecord
  validates :name, uniqueness: true
  has_many :products
  has_many :orders
end

app/models/tax.rb
class Tax < ApplicationRecord
  validates :GST, :PST, presence: true
  has_many :profiles
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def index
    add_breadcrumb "Cart"
  end

  def show
  end

  def addToCart
    session[:cart] ||= []
    session[:cart] << {:id =>params[:id], :qty =>params[:quantity], :price =>params[:price]}

    redirect_to cart_index_path
  end

  def removeFromCart
    if(params[:submit] == "Remove")
      session[:cart].delete_at(params[:number].to_i)
    else
      session[:cart][params[:number].to_i]["qty"] = params[:qty].to_i
    end

    redirect_to cart_index_path
  end

  def checkout
    add_breadcrumb "Cart", cart_index_path
    add_breadcrumb "Checkout", checkout_path

    @total_amount = (session[:total_price].to_f * 100 ).round(0)
    province = @profile.tax
    @taxes = (province.GST + province.PST).round(2)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.order(:name).page(params[:page]).per(9)

    if(params[:filter] && params[:category])
      @status = StatusType.find(params[:filter])
      @products = @products.where(category_id: params[:category])
                          .where(status_type_id: params[:filter])

      add_breadcrumb "Sorting By: #{@status.name}"
    elsif (params[:filter])
      @status = StatusType.find(params[:filter])
      @products = @products.where(status_type_id: params[:filter])

      add_breadcrumb "Sorting By: #{@status.name}"
    end
  end

  def show
    @product = Product.find(params[:id])
    add_breadcrumb "#{@product.category.name}", category_path(@product.category.id)
    add_breadcrumb "#{@product.name}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/status_types_helper.rb
module StatusTypesHelper
end

app/views/products/index.html.erb
<div class="container clearfix col-9 float-right">
  <div class="row">
    <% @products.each do |product| %>
      <div class="card m-4" style="width:200px; position:relative;">
        <a class="nav-link" href = "<%= product_path(:id => product.id)%>" >
          <%= image_tag product.image.thumb.url, class:"card-img-top"%>
          <div class="card-body">
            <h4 class="card-title"><%=  product.name %></h4>
            <p class="card-text" style="position:absolute; bottom:0; right:0;">$<%= product.price%></p>
          </div>
        </a>
      </div>
    <% end %>
  </div>

  <div class="row align-items-center justify-content-center">
    <%= paginate @products %>
  </div>
</div>

app/views/products/show.html.erb
<h4 class="display-4"><%= @product.name%> <small class="text-muted"> in <%= link_to @product.category.name, @product.category%></small></h4>
<div class="row justify-content-around">
  <div class="col-6 mt-4">
    <%= image_tag @product.image.url%>
  </div>
  <div class="col-6 mt-4">
    <%= @product.description%><br>
    $ <%= @product.price%><br>

    <form></form>

    <%= form_tag(cart_add_to_cart_path, method: "get", class:"form-check form-check-inline float-right mt-5" ) do %>
      <%= label_tag("quantity"," Quantity ") %>
      <%= number_field_tag("quantity", 1, class:"form-control m-2", size:2) %>
      <%= hidden_field_tag("id", @product.id)%>
      <%= hidden_field_tag("price", @product.price)%>
      <%= submit_tag("Add To Cart", class:"btn") %>
    <% end %>

  </div>
</div>