config/routes.rb
Rails.application.routes.draw do
  get 'charges/new'
  get 'charges/create'
  get 'profile/index'
  get 'profile/create'
  get 'profile/update'
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Cart Modifications
  get 'cart/add_to_cart', to: "cart#addToCart"
  get 'cart/remove_from_cart', to: "cart#removeFromCart"
  get 'checkout' , to:"cart#checkout"

  # My Profile
  get 'profile/create', to: "profile#create"
  get 'profile/index', to: "profile#index"
  get 'profile/update', to: "profile#update"

  #Orders
  get 'order/add_order', to: 'order#add_order'

  # Stripe routes
  resources :charges, only: [:new, :create]



  resources :products, only: [:show, :index]
  resources :categories, only: [:show, :index]
  resources :pages, only: [:show, :index]
  resources :search, only: [:index] do
    collection do
      get 'results'
    end
  end
  resources :cart, only: [:index]


  get ':permalink', to: 'pages#permalink'

  root 'products#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  mount_uploader :icon, IconUploader
end

app/models/order.rb
class Order < ApplicationRecord
  validates :user_id , :total_price, :status_type_id , presence:true

  belongs_to :user
  belongs_to :status_type

  has_many :ordered_products, dependent: :destroy
  has_many :products, through: :ordered_products, dependent: :destroy
  accepts_nested_attributes_for :ordered_products

end

app/models/ordered_product.rb
class OrderedProduct < ApplicationRecord

  validates :product_id, :order_id, :quantity, :price, presence: true
  validates :quantity, numericality: {greater_than: 0}

  belongs_to :product
  belongs_to :order
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :description, :category,  presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 1}
  validates :name, uniqueness:true

  belongs_to :category
  has_many :ordered_products, dependent: :destroy
  has_many :orders, through: :ordered_products, dependent: :destroy
  belongs_to :status_type

  mount_uploader :image, ImageUploader
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_one :user
  belongs_to :tax
end

app/models/status_type.rb
class StatusType < ApplicationRecord
  validates :name, uniqueness: true
  has_many :products
  has_many :orders
end

app/models/tax.rb
class Tax < ApplicationRecord
  validates :GST, :PST, presence: true
  has_many :profiles
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PerfectFurnishers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render partial: 'shared/navbar'%>

    <div class='container clearfix'>
      <header class="jumbotron">
        <%= render template: "categories/index", collection: @categories%>

      </header>
      <% if notice %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <%= notice%>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <%end%>

      <% if alert %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <%= alert%>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <%end%>

      <ol class="breadcrumb">
        <%= render_breadcrumbs %>
      </ol>
      <% if (params["controller"] == "products" || params["controller"] == "categories" || params["controller"] == "search")%>
        <div class="alert alert-dark w-25 p-3 float-left mt-4">
          <form action="<%= products_path %>"type="Post">
            <div class="display-4">Sort</div><br>
            <div class="mr-10">
              <%= render template: 'status_types/index', collection: @status_types%>
            </div>
            <button type="submit" class="btn btn-primary float-right mt-5">Sort</button>
            <% if (params[:controller] == "categories")%>
              <input type="hidden" name="category" value="<%=params[:id]%>">
            <% end %>
          <form>
          <form action="<%= products_path %>" type="Post">
            <button type="submit" class="btn btn-primary float-left mt-5">All Products</button>
          <form>
        </div>
      <%end%>
      <%= yield %>
    </div>

    <footer class="py-5 bg-dark">
      <div class="container-fluid">
        <p class="m-0 text-center text-white">Copyright &copy; Perfect Furnishers 2018</p>
      </div>
    </footer>
  </body>
</html>

app/views/pages/show.html.erb
<h1><%= @page.title%></h1>
<div>
  <%=raw @page.content%>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container-fluid">
        <a class="navbar-brand" href="<%= root_path%>">PERFECT FURNISHERS</a>

        <%= render template: 'search/index'%>

        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="<%= root_path%>">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="http://localhost:3000/about">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="http://localhost:3000/contact-us">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= cart_index_path%>">Cart</a>
            </li>
          </ul>
        </div>
      </div>
      <% if user_signed_in?%>
        <%if @profile %>
          <a class="btn nav-link" href="<%= profile_index_path %>">My Profile </a>
        <% else %>
          <a class="btn nav-link" href="<%= profile_create_path %>">My Profile </a>
        <% end %>
        <%=link_to "Logout" , destroy_user_session_path, method: :delete, class:"btn nav-link" %>
      <% else %>
        <a class="btn nav-link" href="<%= new_user_registration_path %>">Sign Up </a>
        <a class="btn nav-link" href="<%= new_user_session_path %>">Sign In </a>
      <% end %>
    </nav>